### PR TITLE
Fixes to storing attribute names, gemspec and formatting

### PR DESCRIPTION
**Pull request by abradner**
Before I do any surgery you might want to have a look at these fixes.

The main issue I'm correcting here was attribute names being nuked on import (I'm guessing there was a regression when getting sparse files to work).

There's more on its way, but I figure you don't want a giant lump of code changes to look over

### CODE REVIEW

**Comment by andypayne** [comment]
This looks good. Running the tests, I noticed an error in the use of the CSV library. I've seen this occur in some other code before, it appears that the CSV library is different from Ruby 1.8 to 1.9, as described here:

http://ruby-doc.org/stdlib-1.9.2/libdoc/csv/rdoc/CSV.html#method-c-open

The error is below. Changing the code to use the "foreach" method instead of "open" fixes it for me for both Ruby 1.8.7 and 1.9.3p125. I'll merge this and make the change. Let me know if it works for you as well.

Error text:

# Running tests:

E......

Finished tests in 0.768161s, 9.1127 tests/s, 18.2253 assertions/s.

  1) Error:
test_all_comments_stored(TestArffLib):
NoMethodError: undefined method `[]' for #<CSV:0x007f97cb82eb68>
    ts_rarff.rb:98:in`block in test_all_comments_stored'

7 tests, 14 assertions, 0 failures, 1 errors, 0 skips

**Comment by malavbhavsar** [comment]
@andypayne Can you release this? Please bump.

**Comment by abradner** [comment]
I'm fairly sure all my changes are in my repo abradner/rarff but im
currently a long way from a computer. I have limited 3g if you need me to
do anything can you explain exactly what?

Thanks

**Comment by malavbhavsar** [comment]
@abradner No, it's fine. Take your time. I want to use this in [ai4r](https://github.com/SergioFierens/ai4r) project. So, I wanted this bumped on rubygems. But, then I realized that may be you introduced a bug when you fixed the above things. I have added a PR(#2) with a fail case. Can you look into that when you have time?

**Comment by abradner** [comment]
I am currently traveling through China, so it will be a while. If you need
me to accept or make a pull request i can do, but not much else

**Comment by andypayne** [comment]
I bumped the released gem to 0.2.2 -

http://rubygems.org/gems/rarff

But I haven't had a chance to look into PR #2.

**Pull request merged**
